plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
  Exclude:
    - spec/dummy/db/schema.rb
    - spec/dummy/bin/setup
    - spec/dummy/bin/update
    - bin/rake

# Gemspec

Gemspec/RequiredRubyVersion:
  Enabled: false

# Layout

Layout/LineLength:
  Max: 80

# Metrics

Metrics/BlockLength:
  Exclude:
    - spec/**/*

# Style

Style/MixinUsage:
  Exclude:
    - spec/dummy/bin/*

Style/Documentation:
  Enabled: false

# Rails

Rails:
  Enabled: true

Rails/FilePath:
  EnforcedStyle: slashes

Rails/ApplicationRecord:
  Enabled: false

# RSpec

RSpec/ExampleLength:
  Max: 20

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/VerifiedDoubles:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
